### ISSUE TITLE
Various errors in the command window

### ISSUE THREAD

**Issue by FeBe95** [pichillilorenzo/JavaScriptEnhancements#12]
Just going to post them here, so you can have a look at the lines of your code:

## Start up
```
Exception in thread DownloadCanIuseJsonData:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "C:\Users\Felix\AppData\Roaming\Sublime Text 3\Packages\JavaScript Enhancements\_generated_2018_01_09_at_00_20_38.py", line 5144, in donwload_can_i_use_json_data
    os.remove(path_to_test_can_i_use_data)
PermissionError: [WinError 32] PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\Felix\\AppData\\Roaming\\Sublime Text 3\\Packages\\JavaScript Enhancements\\helper\\can_i_use\\can_i_use_data2.json'
```

## Hovering a word/variable/function
```
Exception in thread JavaScriptEnhancementsCompletions:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "C:\Users\Felix\AppData\Roaming\Sublime Text 3\Packages\JavaScript Enhancements\_generated_2018_01_09_at_00_20_38.py", line 3673, in <lambda>
    javascript_completions_thread_list.append(Util.create_and_start_thread(target=lambda: self.on_query_completions_async(view, "", locations, len(javascript_completions_thread_list)+1), thread_name="JavaScriptEnhancementsCompletions"))
  File "C:\Users\Felix\AppData\Roaming\Sublime Text 3\Packages\JavaScript Enhancements\_generated_2018_01_09_at_00_20_38.py", line 3541, in on_query_completions_async
    deps = flow_parse_cli_dependencies(view, add_magic_token=True, cursor_pos=locations[0])
  File "C:\Users\Felix\AppData\Roaming\Sublime Text 3\Packages\JavaScript Enhancements\_generated_2018_01_09_at_00_20_38.py", line 1328, in flow_parse_cli_dependencies
    project_root = find_flow_config(filename)
  File "C:\Users\Felix\AppData\Roaming\Sublime Text 3\Packages\JavaScript Enhancements\_generated_2018_01_09_at_00_20_38.py", line 1319, in find_flow_config
    return find_flow_config(potential_root)

  ... (~1000x this line)

  File "C:\Users\Felix\AppData\Roaming\Sublime Text 3\Packages\JavaScript Enhancements\_generated_2018_01_09_at_00_20_38.py", line 1319, in find_flow_config
    return find_flow_config(potential_root)
  File "C:\Users\Felix\AppData\Roaming\Sublime Text 3\Packages\JavaScript Enhancements\_generated_2018_01_09_at_00_20_38.py", line 1315, in find_flow_config
    potential_root = os.path.dirname(filename)
  File "./python3.3/ntpath.py", line 256, in dirname
  File "./python3.3/ntpath.py", line 220, in split
  File "./python3.3/ntpath.py", line 161, in splitdrive
  File "./python3.3/ntpath.py", line 39, in _get_empty
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

- Sublime Text 3 build: 3143
- OS: Windows 64bit
- JavaScript Enhancements version: 0.11.1

**Comment by FeBe95** [comment]
Different error now in v0.11.11 that doesn't affect my workflow though:

```
Traceback (most recent call last):
  File "C:\Users\Felix\AppData\Roaming\Sublime Text 3\Packages\JavaScript Enhancements\_generated_2018_01_10_at_20_34_18.py", line 248, in execute_check_output
    os.unlink(fp.name)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'c:\\users\\felix\\appdata\\local\\temp\\tmpa127lp'

Traceback (most recent call last):
  File "C:\Users\Felix\AppData\Roaming\Sublime Text 3\Packages\JavaScript Enhancements\_generated_2018_01_10_at_20_34_18.py", line 248, in execute_check_output
    os.unlink(fp.name)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'c:\\users\\felix\\appdata\\local\\temp\\tmpa127lp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Felix\AppData\Roaming\Sublime Text 3\Packages\JavaScript Enhancements\_generated_2018_01_10_at_20_34_18.py", line 3616, in <lambda>
    view, prefix, locations
  File "C:\Users\Felix\AppData\Roaming\Sublime Text 3\Packages\JavaScript Enhancements\_generated_2018_01_10_at_20_34_18.py", line 3670, in on_query_completions_async
    use_node=use_node
  File "C:\Users\Felix\AppData\Roaming\Sublime Text 3\Packages\JavaScript Enhancements\_generated_2018_01_10_at_20_34_18.py", line 322, in execute_check_output
    os.unlink(fp.name)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'c:\\users\\felix\\appdata\\local\\temp\\tmpa127lp'
```

**Comment by pichillilorenzo** [comment]
Tomorrow I'm going to release the new version with the changes!

**Comment by pichillilorenzo** [comment]
@FeBe95 I released the new version!
