### ISSUE TITLE
New error breaks whole plugin 

### ISSUE THREAD

**Issue by FeBe95** [pichillilorenzo/JavaScriptEnhancements#13]
I am very sorry, but the new version 13.0 breaks the plugin completely :(

## Error in the console at start up:

```
reloading plugin JavaScript Enhancements._generated_2018_01_14_at_01_20_41
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\Felix\AppData\Roaming\Sublime Text 3\Packages\JavaScript Enhancements\_generated_2018_01_14_at_01_20_41.py", line 439, in <module>
    from six import iteritems
ImportError: No module named 'six'
```

No further errors appear when trying to use the plugin (such as activating items in the "Tools->JSE" menu or writing JavaScript code samples)

### Specifications

- Sublime Text 3 build: 3143
- OS: Windows x64
- JavaScript Enhancements version: 13.0

**Comment by pichillilorenzo** [comment]
@FeBe95 With the new v0.13.1 release should work now! 👍

**Comment by FeBe95** [comment]
Yes, it does, no more errors now ;) 👍
