### ISSUE TITLE
use on windows

### ISSUE THREAD

**Issue by New-Hands** [pichillilorenzo/JavaScriptEnhancements#15]
### Sublime Text console logs 

Traceback (most recent call last):
  File "C:\Users\lst\AppData\Roaming\Sublime Text 3\Packages\JavaScript Enhancements\_generated_2018_01_14_at_17_26_33.py", line 244, in execute_check_output
    args, shell=True, stderr=subprocess.STDOUT, timeout=10
  File "./python3.3/subprocess.py", line 589, in check_output
subprocess.CalledProcessError: Command '"C:\\Users\\lst\\AppData\\Roaming\\Sublime Text 3\\Packages\\JavaScript Enhancements\\node_modules\\.bin\\flow.cmd" "ast" "--from" "sublime_text" < "c:\\users\\lst\\appdata\\local\\temp\\tmp_qofgv"' returned non-zero exit status 1

### Screenshots

![image](https://user-images.githubusercontent.com/13027796/34990937-d7611dfe-fb02-11e7-9f82-2bec260e059a.png)

### Steps to Reproduce the Problem

1.can not auto completion
1.i hava set the path when i install node.js
1.

### Specifications

- Sublime Text 3 build:3143
- OS:windows
- JavaScript Enhancements version:

**Comment by pichillilorenzo** [comment]
@New-Hands which version of Windows do you have? Could you post here the settings file of the plugin? Furthermore, have you tried to reinstall it? Thanks!

**Comment by pichillilorenzo** [comment]
@New-Hands I updated the plugin! Could you try it again please? If it doesn't work again, paste here the console logs. Thanks!
