### ISSUE TITLE
Error on Windows

### ISSUE THREAD

**Issue by FeBe95** [pichillilorenzo/JavaScriptEnhancements#2]
Doesn't work at all at the moment (Windows x64, ST3-3143):
```
reloading plugin JavaScriptEnhancements._generated_2017_05_31_at_00_57_17
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\Felix\AppData\Roaming\Sublime Text 3\Packages\JavaScriptEnhancements\_generated_2017_05_31_at_00_57_17.py", line 599, in <module>
    import re, urllib, shutil, traceback, threading, time, os, hashlib, json, multiprocessing, shlex, pty
  File "./python3.3/pty.py", line 11, in <module>
  File "./python3.3/tty.py", line 5, in <module>
ImportError: No module named 'termios'

```

**Comment by pichillilorenzo** [comment]
Hi @FeBe95, as you can see on the readme file, it is not ready yet! I have not been able to work on it for months! I'm planning to restart when i will have more time. Sorry!

**Comment by FeBe95** [comment]
Yes, I am aware of that, I just wanted to let you know ;)
I’m looking forward to using the final plugin, no matter when!

**Comment by pichillilorenzo** [comment]
Hey @FeBe95, I just released the support for Windows! Let me know 😄

**Comment by joeyespo** [comment]
Awesome! Was going to open a new issue this evening for Windows support, and just saw this. Nice job 👍

**Comment by FeBe95** [comment]
@pichillilorenzo thanks for looking in to this, it works now as expected 👍
I will open another issue about some other unexpected behavior shortly though 😄
