### ISSUE TITLE
Had to manually run `npm install`

### ISSUE THREAD

**Issue by davidnormo** [pichillilorenzo/JavaScriptEnhancements#40]
### Expected Behavior
1. Install the package
2. Add the following to a .js file: `let a = 'abc'; a.`
3. Then hit ctrl+space to see autocompletions
4. Dropdown should appear with options

### Actual Behavior
1. Install the package
2. Add the following to a .js file: `let a = 'abc'; a.`
3. Then hit ctrl+space to see autocompletions
3. Error in sublime console (ctrl+`):
```
Error: Cannot find module '~/Library/Application Support/Sublime Text 3/Packages/JavaScript Enhancements/node_modules/.bin/flow'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

To fix I manually cd'd into the Javascript Enhancements directory and ran `npm install`.

### Specifications

- Sublime Text 3 build:  3143
- OS: MacOS Sierra 10.12.6
- JavaScript Enhancements version: 0.16.1

Thanks for making such a helpful package 👍

**Comment by pichillilorenzo** [comment]
did you get an error about `npm` before this in the Sublime Text console??

**Comment by pichillilorenzo** [comment]
@davidnormo any news?

**Comment by orangecoloured** [comment]
Having the same issue.
Why is it looking for a local flow when I have it installed globally?

**Comment by pichillilorenzo** [comment]
@orangecoloured because I specify specific version of Flow. If the Flow team changes its API, I need to change the behaviour of the plugin accordingly. For example if you have an older version of flow, maybe there could be errors because your version doesn't have a particular feature or maybe it works in a different way. However I will add also the possibility to specify a custom path for Flow per project, but, depending on the flow version, some features could not be available. Any advice is welcome!

However if you had the same issue, maybe some other features that uses node.js or npm could not work as well, so can you post Sublime Text console logs? Also, what OS do you have? 

Thanks!

**Comment by orangecoloured** [comment]
@pichillilorenzo it's working now! For some reason it didn't download anything and didn't work. I had to restart ST twice to see that it was installing its packages. So, everything's fine now. Thanks!

**Comment by pichillilorenzo** [comment]
@orangecoloured Thank you for the support!
