### ISSUE TITLE
sublime_text_build_4099_x64  python33

### ISSUE THREAD

**Issue by ghost** [pichillilorenzo/JavaScriptEnhancements#81]
[###](url) Expected Behavior

### Sublime Text console logs 

Traceback (most recent call last):
reloading python 3.3 plugin JavaScript Enhancements.main
Traceback (most recent call last):
  File "D:\Program Tools\sublime_text_build_4099_x64\Lib\python33\sublime_plugin.py", line 310, in reload_plugin
    load_module(m)
  File "D:\Program Tools\sublime_text_build_4099_x64\Lib\python33\sublime_plugin.py", line 343, in load_module
    decorate_handler(t, method_name)
  File "D:\Program Tools\sublime_text_build_4099_x64\Lib\python33\sublime_plugin.py", line 226, in decorate_handler
    method = cls.__dict__[method_name]
KeyError: 'on_new'
reloading python 3.3 plugin LocalizedMenu.Localize
reloading python 3.3 plugin NodeRequirer.NodeRequirer
### Steps to Reproduce the Problem

1.
1.
1.

### Specifications

- Sublime Text 3 build:
- OS:
- JavaScript Enhancements version:

**Comment by ghost** [comment]
1. 
[python33.zip](https://github.com/pichillilorenzo/JavaScriptEnhancements/files/6236299/python33.zip)

**Comment by joket1999** [comment]
The same error with me.
